/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PlannedMeal } from "./components/meal-plan-day/meal-plan-day";
import { RecipeFormData } from "./components/recipe-form/recipe-form";
export { PlannedMeal } from "./components/meal-plan-day/meal-plan-day";
export { RecipeFormData } from "./components/recipe-form/recipe-form";
export namespace Components {
    /**
     * Generic modal dialog. Body content is provided via the default slot.
     */
    interface AppModal {
        /**
          * @default ''
         */
        "modalTitle": string;
        /**
          * @default false
         */
        "open": boolean;
    }
    /**
     * Simple notification toast. Auto-dismisses after `duration` ms if > 0.
     */
    interface AppToast {
        /**
          * @default 3000
         */
        "duration": number;
        /**
          * @default ''
         */
        "message": string;
        /**
          * @default 'info'
         */
        "type": 'success' | 'error' | 'info';
    }
    interface MealPlanDay {
        /**
          * @default ''
         */
        "day": string;
        /**
          * Optional emoji/icon shown next to the label, e.g. "🌅"
          * @default ''
         */
        "icon": string;
        /**
          * @default []
         */
        "meals": PlannedMeal[];
    }
    /**
     * Displays a summary of a recipe (image, title, category) inside a card.
     * Emits `cardClick` when the card body is clicked and `favoriteToggle`
     * when the favorite button is pressed. Accepts a named `actions` slot
     * for extra buttons supplied by the consuming app.
     */
    interface RecipeCard {
        /**
          * Category label
          * @default ''
         */
        "category": string;
        /**
          * Cuisine label
          * @default ''
         */
        "cuisine": string;
        /**
          * Whether this recipe is currently favorited
          * @default false
         */
        "favorite": boolean;
        /**
          * Image URL
         */
        "image": string;
        /**
          * Recipe title (named recipeTitle, not title, to avoid colliding with the native HTML title/tooltip attribute every element already has)
         */
        "recipeTitle": string;
    }
    /**
     * Renders a row of selectable filter chips (e.g. categories/cuisines).
     * `categories` accepts either a JSON string array or an actual array
     * (Stencil auto-parses complex props passed as attributes).
     * Emits `filterChange` with the selected value ('' = all).
     */
    interface RecipeFilterBar {
        /**
          * @default ''
         */
        "active": string;
        /**
          * @default []
         */
        "categories": string[];
    }
    interface RecipeForm {
        /**
          * @default [   'American', 'British', 'Chinese', 'Croatian', 'Dutch', 'Egyptian',   'Filipino', 'French', 'Greek', 'Indian', 'Irish', 'Italian', 'Jamaican',   'Japanese', 'Kenyan', 'Malaysian', 'Mexican', 'Moroccan', 'Polish',   'Portuguese', 'Russian', 'Spanish', 'Thai', 'Tunisian', 'Turkish',   'Vietnamese', 'Other', ]
         */
        "areas": string[];
        /**
          * @default [   'Beef', 'Breakfast', 'Chicken', 'Dessert', 'Goat', 'Lamb',   'Miscellaneous', 'Pasta', 'Pork', 'Seafood', 'Side', 'Starter',   'Vegan', 'Vegetarian', 'Other', ]
         */
        "categories": string[];
        /**
          * @default []
         */
        "extraAreas": string[];
        /**
          * @default []
         */
        "extraCategories": string[];
        "initialData": RecipeFormData | string;
    }
    /**
     * 5-star rating. Read-only display or interactive input.
     */
    interface RecipeRating {
        /**
          * @default 5
         */
        "max": number;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default 0
         */
        "value": number;
    }
    /**
     * A debounced search input. Emits `search` with the current value
     * after the user stops typing (default 350ms) or presses Enter.
     */
    interface RecipeSearchBar {
        /**
          * @default 350
         */
        "debounceMs": number;
        /**
          * @default 'Search recipes...'
         */
        "placeholder": string;
        /**
          * @default true
         */
        "showSearchButton": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface AppModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppModalElement;
}
export interface AppToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppToastElement;
}
export interface MealPlanDayCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealPlanDayElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface RecipeFilterBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeFilterBarElement;
}
export interface RecipeFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeFormElement;
}
export interface RecipeRatingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeRatingElement;
}
export interface RecipeSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeSearchBarElement;
}
declare global {
    interface HTMLAppModalElementEventMap {
        "close": void;
    }
    /**
     * Generic modal dialog. Body content is provided via the default slot.
     */
    interface HTMLAppModalElement extends Components.AppModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppModalElementEventMap>(type: K, listener: (this: HTMLAppModalElement, ev: AppModalCustomEvent<HTMLAppModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppModalElementEventMap>(type: K, listener: (this: HTMLAppModalElement, ev: AppModalCustomEvent<HTMLAppModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppModalElement: {
        prototype: HTMLAppModalElement;
        new (): HTMLAppModalElement;
    };
    interface HTMLAppToastElementEventMap {
        "dismiss": void;
    }
    /**
     * Simple notification toast. Auto-dismisses after `duration` ms if > 0.
     */
    interface HTMLAppToastElement extends Components.AppToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppToastElementEventMap>(type: K, listener: (this: HTMLAppToastElement, ev: AppToastCustomEvent<HTMLAppToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppToastElementEventMap>(type: K, listener: (this: HTMLAppToastElement, ev: AppToastCustomEvent<HTMLAppToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppToastElement: {
        prototype: HTMLAppToastElement;
        new (): HTMLAppToastElement;
    };
    interface HTMLMealPlanDayElementEventMap {
        "assignMeal": { day: string };
        "removeMeal": { day: string; mealId: string };
    }
    interface HTMLMealPlanDayElement extends Components.MealPlanDay, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealPlanDayElementEventMap>(type: K, listener: (this: HTMLMealPlanDayElement, ev: MealPlanDayCustomEvent<HTMLMealPlanDayElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealPlanDayElementEventMap>(type: K, listener: (this: HTMLMealPlanDayElement, ev: MealPlanDayCustomEvent<HTMLMealPlanDayElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealPlanDayElement: {
        prototype: HTMLMealPlanDayElement;
        new (): HTMLMealPlanDayElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "favoriteToggle": { favorite: boolean };
        "cardClick": void;
    }
    /**
     * Displays a summary of a recipe (image, title, category) inside a card.
     * Emits `cardClick` when the card body is clicked and `favoriteToggle`
     * when the favorite button is pressed. Accepts a named `actions` slot
     * for extra buttons supplied by the consuming app.
     */
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeFilterBarElementEventMap {
        "filterChange": { value: string };
    }
    /**
     * Renders a row of selectable filter chips (e.g. categories/cuisines).
     * `categories` accepts either a JSON string array or an actual array
     * (Stencil auto-parses complex props passed as attributes).
     * Emits `filterChange` with the selected value ('' = all).
     */
    interface HTMLRecipeFilterBarElement extends Components.RecipeFilterBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeFilterBarElementEventMap>(type: K, listener: (this: HTMLRecipeFilterBarElement, ev: RecipeFilterBarCustomEvent<HTMLRecipeFilterBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeFilterBarElementEventMap>(type: K, listener: (this: HTMLRecipeFilterBarElement, ev: RecipeFilterBarCustomEvent<HTMLRecipeFilterBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeFilterBarElement: {
        prototype: HTMLRecipeFilterBarElement;
        new (): HTMLRecipeFilterBarElement;
    };
    interface HTMLRecipeFormElementEventMap {
        "save": RecipeFormData;
        "cancel": void;
    }
    interface HTMLRecipeFormElement extends Components.RecipeForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeFormElement: {
        prototype: HTMLRecipeFormElement;
        new (): HTMLRecipeFormElement;
    };
    interface HTMLRecipeRatingElementEventMap {
        "ratingChange": { value: number };
    }
    /**
     * 5-star rating. Read-only display or interactive input.
     */
    interface HTMLRecipeRatingElement extends Components.RecipeRating, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeRatingElementEventMap>(type: K, listener: (this: HTMLRecipeRatingElement, ev: RecipeRatingCustomEvent<HTMLRecipeRatingElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeRatingElementEventMap>(type: K, listener: (this: HTMLRecipeRatingElement, ev: RecipeRatingCustomEvent<HTMLRecipeRatingElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeRatingElement: {
        prototype: HTMLRecipeRatingElement;
        new (): HTMLRecipeRatingElement;
    };
    interface HTMLRecipeSearchBarElementEventMap {
        "search": { value: string };
    }
    /**
     * A debounced search input. Emits `search` with the current value
     * after the user stops typing (default 350ms) or presses Enter.
     */
    interface HTMLRecipeSearchBarElement extends Components.RecipeSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeSearchBarElementEventMap>(type: K, listener: (this: HTMLRecipeSearchBarElement, ev: RecipeSearchBarCustomEvent<HTMLRecipeSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeSearchBarElementEventMap>(type: K, listener: (this: HTMLRecipeSearchBarElement, ev: RecipeSearchBarCustomEvent<HTMLRecipeSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeSearchBarElement: {
        prototype: HTMLRecipeSearchBarElement;
        new (): HTMLRecipeSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "app-modal": HTMLAppModalElement;
        "app-toast": HTMLAppToastElement;
        "meal-plan-day": HTMLMealPlanDayElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-filter-bar": HTMLRecipeFilterBarElement;
        "recipe-form": HTMLRecipeFormElement;
        "recipe-rating": HTMLRecipeRatingElement;
        "recipe-search-bar": HTMLRecipeSearchBarElement;
    }
}
declare namespace LocalJSX {
    /**
     * Generic modal dialog. Body content is provided via the default slot.
     */
    interface AppModal {
        /**
          * @default ''
         */
        "modalTitle"?: string;
        "onClose"?: (event: AppModalCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * Simple notification toast. Auto-dismisses after `duration` ms if > 0.
     */
    interface AppToast {
        /**
          * @default 3000
         */
        "duration"?: number;
        /**
          * @default ''
         */
        "message"?: string;
        "onDismiss"?: (event: AppToastCustomEvent<void>) => void;
        /**
          * @default 'info'
         */
        "type"?: 'success' | 'error' | 'info';
    }
    interface MealPlanDay {
        /**
          * @default ''
         */
        "day"?: string;
        /**
          * Optional emoji/icon shown next to the label, e.g. "🌅"
          * @default ''
         */
        "icon"?: string;
        /**
          * @default []
         */
        "meals"?: PlannedMeal[];
        "onAssignMeal"?: (event: MealPlanDayCustomEvent<{ day: string }>) => void;
        "onRemoveMeal"?: (event: MealPlanDayCustomEvent<{ day: string; mealId: string }>) => void;
    }
    /**
     * Displays a summary of a recipe (image, title, category) inside a card.
     * Emits `cardClick` when the card body is clicked and `favoriteToggle`
     * when the favorite button is pressed. Accepts a named `actions` slot
     * for extra buttons supplied by the consuming app.
     */
    interface RecipeCard {
        /**
          * Category label
          * @default ''
         */
        "category"?: string;
        /**
          * Cuisine label
          * @default ''
         */
        "cuisine"?: string;
        /**
          * Whether this recipe is currently favorited
          * @default false
         */
        "favorite"?: boolean;
        /**
          * Image URL
         */
        "image"?: string;
        /**
          * Fired when the card (excluding the favorite button) is clicked
         */
        "onCardClick"?: (event: RecipeCardCustomEvent<void>) => void;
        /**
          * Fired when the favorite button is toggled
         */
        "onFavoriteToggle"?: (event: RecipeCardCustomEvent<{ favorite: boolean }>) => void;
        /**
          * Recipe title (named recipeTitle, not title, to avoid colliding with the native HTML title/tooltip attribute every element already has)
         */
        "recipeTitle"?: string;
    }
    /**
     * Renders a row of selectable filter chips (e.g. categories/cuisines).
     * `categories` accepts either a JSON string array or an actual array
     * (Stencil auto-parses complex props passed as attributes).
     * Emits `filterChange` with the selected value ('' = all).
     */
    interface RecipeFilterBar {
        /**
          * @default ''
         */
        "active"?: string;
        /**
          * @default []
         */
        "categories"?: string[];
        "onFilterChange"?: (event: RecipeFilterBarCustomEvent<{ value: string }>) => void;
    }
    interface RecipeForm {
        /**
          * @default [   'American', 'British', 'Chinese', 'Croatian', 'Dutch', 'Egyptian',   'Filipino', 'French', 'Greek', 'Indian', 'Irish', 'Italian', 'Jamaican',   'Japanese', 'Kenyan', 'Malaysian', 'Mexican', 'Moroccan', 'Polish',   'Portuguese', 'Russian', 'Spanish', 'Thai', 'Tunisian', 'Turkish',   'Vietnamese', 'Other', ]
         */
        "areas"?: string[];
        /**
          * @default [   'Beef', 'Breakfast', 'Chicken', 'Dessert', 'Goat', 'Lamb',   'Miscellaneous', 'Pasta', 'Pork', 'Seafood', 'Side', 'Starter',   'Vegan', 'Vegetarian', 'Other', ]
         */
        "categories"?: string[];
        /**
          * @default []
         */
        "extraAreas"?: string[];
        /**
          * @default []
         */
        "extraCategories"?: string[];
        "initialData"?: RecipeFormData | string;
        "onCancel"?: (event: RecipeFormCustomEvent<void>) => void;
        "onSave"?: (event: RecipeFormCustomEvent<RecipeFormData>) => void;
    }
    /**
     * 5-star rating. Read-only display or interactive input.
     */
    interface RecipeRating {
        /**
          * @default 5
         */
        "max"?: number;
        "onRatingChange"?: (event: RecipeRatingCustomEvent<{ value: number }>) => void;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default 0
         */
        "value"?: number;
    }
    /**
     * A debounced search input. Emits `search` with the current value
     * after the user stops typing (default 350ms) or presses Enter.
     */
    interface RecipeSearchBar {
        /**
          * @default 350
         */
        "debounceMs"?: number;
        "onSearch"?: (event: RecipeSearchBarCustomEvent<{ value: string }>) => void;
        /**
          * @default 'Search recipes...'
         */
        "placeholder"?: string;
        /**
          * @default true
         */
        "showSearchButton"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface AppModalAttributes {
        "open": boolean;
        "modalTitle": string;
    }
    interface AppToastAttributes {
        "message": string;
        "type": 'success' | 'error' | 'info';
        "duration": number;
    }
    interface MealPlanDayAttributes {
        "day": string;
        "icon": string;
    }
    interface RecipeCardAttributes {
        "recipeTitle": string;
        "image": string;
        "category": string;
        "cuisine": string;
        "favorite": boolean;
    }
    interface RecipeFilterBarAttributes {
        "active": string;
    }
    interface RecipeFormAttributes {
        "initialData": RecipeFormData | string;
    }
    interface RecipeRatingAttributes {
        "value": number;
        "readonly": boolean;
        "max": number;
    }
    interface RecipeSearchBarAttributes {
        "placeholder": string;
        "value": string;
        "debounceMs": number;
        "showSearchButton": boolean;
    }

    interface IntrinsicElements {
        "app-modal": Omit<AppModal, keyof AppModalAttributes> & { [K in keyof AppModal & keyof AppModalAttributes]?: AppModal[K] } & { [K in keyof AppModal & keyof AppModalAttributes as `attr:${K}`]?: AppModalAttributes[K] } & { [K in keyof AppModal & keyof AppModalAttributes as `prop:${K}`]?: AppModal[K] };
        "app-toast": Omit<AppToast, keyof AppToastAttributes> & { [K in keyof AppToast & keyof AppToastAttributes]?: AppToast[K] } & { [K in keyof AppToast & keyof AppToastAttributes as `attr:${K}`]?: AppToastAttributes[K] } & { [K in keyof AppToast & keyof AppToastAttributes as `prop:${K}`]?: AppToast[K] };
        "meal-plan-day": Omit<MealPlanDay, keyof MealPlanDayAttributes> & { [K in keyof MealPlanDay & keyof MealPlanDayAttributes]?: MealPlanDay[K] } & { [K in keyof MealPlanDay & keyof MealPlanDayAttributes as `attr:${K}`]?: MealPlanDayAttributes[K] } & { [K in keyof MealPlanDay & keyof MealPlanDayAttributes as `prop:${K}`]?: MealPlanDay[K] };
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] };
        "recipe-filter-bar": Omit<RecipeFilterBar, keyof RecipeFilterBarAttributes> & { [K in keyof RecipeFilterBar & keyof RecipeFilterBarAttributes]?: RecipeFilterBar[K] } & { [K in keyof RecipeFilterBar & keyof RecipeFilterBarAttributes as `attr:${K}`]?: RecipeFilterBarAttributes[K] } & { [K in keyof RecipeFilterBar & keyof RecipeFilterBarAttributes as `prop:${K}`]?: RecipeFilterBar[K] };
        "recipe-form": Omit<RecipeForm, keyof RecipeFormAttributes> & { [K in keyof RecipeForm & keyof RecipeFormAttributes]?: RecipeForm[K] } & { [K in keyof RecipeForm & keyof RecipeFormAttributes as `attr:${K}`]?: RecipeFormAttributes[K] } & { [K in keyof RecipeForm & keyof RecipeFormAttributes as `prop:${K}`]?: RecipeForm[K] };
        "recipe-rating": Omit<RecipeRating, keyof RecipeRatingAttributes> & { [K in keyof RecipeRating & keyof RecipeRatingAttributes]?: RecipeRating[K] } & { [K in keyof RecipeRating & keyof RecipeRatingAttributes as `attr:${K}`]?: RecipeRatingAttributes[K] } & { [K in keyof RecipeRating & keyof RecipeRatingAttributes as `prop:${K}`]?: RecipeRating[K] };
        "recipe-search-bar": Omit<RecipeSearchBar, keyof RecipeSearchBarAttributes> & { [K in keyof RecipeSearchBar & keyof RecipeSearchBarAttributes]?: RecipeSearchBar[K] } & { [K in keyof RecipeSearchBar & keyof RecipeSearchBarAttributes as `attr:${K}`]?: RecipeSearchBarAttributes[K] } & { [K in keyof RecipeSearchBar & keyof RecipeSearchBarAttributes as `prop:${K}`]?: RecipeSearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Generic modal dialog. Body content is provided via the default slot.
             */
            "app-modal": LocalJSX.IntrinsicElements["app-modal"] & JSXBase.HTMLAttributes<HTMLAppModalElement>;
            /**
             * Simple notification toast. Auto-dismisses after `duration` ms if > 0.
             */
            "app-toast": LocalJSX.IntrinsicElements["app-toast"] & JSXBase.HTMLAttributes<HTMLAppToastElement>;
            "meal-plan-day": LocalJSX.IntrinsicElements["meal-plan-day"] & JSXBase.HTMLAttributes<HTMLMealPlanDayElement>;
            /**
             * Displays a summary of a recipe (image, title, category) inside a card.
             * Emits `cardClick` when the card body is clicked and `favoriteToggle`
             * when the favorite button is pressed. Accepts a named `actions` slot
             * for extra buttons supplied by the consuming app.
             */
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            /**
             * Renders a row of selectable filter chips (e.g. categories/cuisines).
             * `categories` accepts either a JSON string array or an actual array
             * (Stencil auto-parses complex props passed as attributes).
             * Emits `filterChange` with the selected value ('' = all).
             */
            "recipe-filter-bar": LocalJSX.IntrinsicElements["recipe-filter-bar"] & JSXBase.HTMLAttributes<HTMLRecipeFilterBarElement>;
            "recipe-form": LocalJSX.IntrinsicElements["recipe-form"] & JSXBase.HTMLAttributes<HTMLRecipeFormElement>;
            /**
             * 5-star rating. Read-only display or interactive input.
             */
            "recipe-rating": LocalJSX.IntrinsicElements["recipe-rating"] & JSXBase.HTMLAttributes<HTMLRecipeRatingElement>;
            /**
             * A debounced search input. Emits `search` with the current value
             * after the user stops typing (default 350ms) or presses Enter.
             */
            "recipe-search-bar": LocalJSX.IntrinsicElements["recipe-search-bar"] & JSXBase.HTMLAttributes<HTMLRecipeSearchBarElement>;
        }
    }
}
